# Generated by Django 2.2.11 on 2020-03-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200307_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Course'),
        ),
    ]
