# Generated by Django 2.2.11 on 2020-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200308_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_name',
        ),
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.ManyToManyField(default='', to='blog.Course'),
        ),
    ]
