# Generated by Django 2.2.11 on 2020-03-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200308_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.ManyToManyField(to='blog.Course'),
        ),
    ]
