# Generated by Django 2.2.11 on 2020-03-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200314_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
