# Generated by Django 2.2.11 on 2020-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200317_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.ManyToManyField(to='blog.Student'),
        ),
    ]
