# Generated by Django 2.2.11 on 2020-03-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200321_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mark',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Student'),
        ),
    ]
