# Generated by Django 2.2.11 on 2020-03-22 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200321_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course_name',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
