# Generated by Django 2.2.11 on 2020-03-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200322_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course',
            new_name='course_name',
        ),
    ]
