# Generated by Django 2.2.11 on 2020-08-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200322_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Instructor'),
        ),
    ]
